version: "3"
services:
  react-app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./node_modules:/app/node_modules
    env_file:
      - .env.dev
    environment:
      - REACT_APP_API_URL=localhost:3000
