version: "3"
services:
  react-app-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        - REACT_APP_API_URL=localhost:3000
    ports:
      - "80:80"
    env_file:
      - .env.prod
   