export const FUSE_TNC_MODAL = 'FUSE_TNC_MODAL';
export const FUSE_OTHER_TNC__MODAL = 'FUSE_OTHER_TNC__MODAL';
export const FUSE_OTHER_TNC_PROCESSING__MODAL = 'FUSE_OTHER_TNC_PROCESSING__MODAL';
export const FUSE_DETAILS__MODAL = 'FUSE_DETAILS__MODAL';
export const FUSE_PROCESS__MODAL = 'FUSE_PROCESS__MODAL';
export const FUSE_SUCCESS__MODAL = 'FUSE_SUCCESS__MODAL';

// auth modal
export const LOGIN_MODAL = 'LOGIN_MODAL';
export const SIGN_UP_MODAL = 'SIGN_UP_MODAL';
export const FORGOT_PASSWORD_MODAL = 'FORGOT_PASSWORD_MODAL';
export const VERIFY_OTP_MODAL = 'VERIFY_OTP_MODAL';
export const RESET_PASSWORD_MODAL = 'RESET_PASSWORD_MODAL';
export const LOGOUT_MODAL = 'LOGOUT_MODAL';

//edit profile modal
export const EDIT_PROFILE_MODAL = 'EDIT_PROFILE_MODAL';

// nft modal
export const WALLET_NETWORK_SWITCH_MODAL = 'WALLET_NETWORK_SWITCH_MODAL';
export const INVALID_WALLET_MODAL = 'INVALID_WALLET_MODAL';
export const WALLET_REGISTER_MODAL = 'WALLET_REGISTER_MODAL';


